//package com.example.demo.entity;
//// Generated 31-ago-2017 13:03:04 by Hibernate Tools 5.2.3.Final
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import static javax.persistence.GenerationType.IDENTITY;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.Table;
//
///**
// * Course generated by hbm2java
// */
//@Entity
//@Table(name = "course", catalog = "academyweb")
//public class CourseAutomatica implements java.io.Serializable {
//
//	private Integer id;
//	private TeacherAutomatica teacher;
//	private String name;
//	private String themes;
//
//	public CourseAutomatica() {
//	}
//
//	public CourseAutomatica(TeacherAutomatica teacher, String name, String themes) {
//		this.teacher = teacher;
//		this.name = name;
//		this.themes = themes;
//	}
//
//	@Id
//	@GeneratedValue(strategy = IDENTITY)
//
//	@Column(name = "id", unique = true, nullable = false)
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "idteacher", nullable = false)
//	public TeacherAutomatica getTeacher() {
//		return this.teacher;
//	}
//
//	public void setTeacher(TeacherAutomatica teacher) {
//		this.teacher = teacher;
//	}
//
//	@Column(name = "name", nullable = false, length = 45)
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	@Column(name = "themes", nullable = false, length = 45)
//	public String getThemes() {
//		return this.themes;
//	}
//
//	public void setThemes(String themes) {
//		this.themes = themes;
//	}
//
//}
