//package com.example.demo.entity;
//// Generated 31-ago-2017 13:03:04 by Hibernate Tools 5.2.3.Final
//
//import java.util.HashSet;
//import java.util.Set;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import static javax.persistence.GenerationType.IDENTITY;
//import javax.persistence.Id;
//import javax.persistence.OneToMany;
//import javax.persistence.Table;
//
///**
// * Teacher generated by hbm2java
// */
//@Entity
//@Table(name = "teacher", catalog = "academyweb")
//public class TeacherAutomatica implements java.io.Serializable {
//
//	private Integer id;
//	private String name;
//	private Set courses = new HashSet(0);
//
//	public TeacherAutomatica() {
//	}
//
//	public TeacherAutomatica(String name) {
//		this.name = name;
//	}
//
//	public TeacherAutomatica(String name, Set courses) {
//		this.name = name;
//		this.courses = courses;
//	}
//
//	@Id
//	@GeneratedValue(strategy = IDENTITY)
//
//	@Column(name = "id", unique = true, nullable = false)
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	@Column(name = "name", nullable = false, length = 20)
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teacher")
//	public Set getCourses() {
//		return this.courses;
//	}
//
//	public void setCourses(Set courses) {
//		this.courses = courses;
//	}
//
//}
